version: '3.7'

services:
  #database
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=jwt
    volumes:
      - jwt-pg-data:/bitnami/postgresql
    #networks:
    # - app-network

  #api
  #api:
  #  build: .
  #  container_name: api_autenticacao
  #  environment:
  #    - DATABASE_URL=DATABASE_URL="postgresql://docker:docker@localhost:5432/jwt"
  #  ports:
  #    - "3333:3333"
  #  volumes:
  #    - .:/app
  #  depends_on:
  #    - postgres
  #  networks:
  #    - app-network

volumes:
  jwt-pg-data:

#networks:
#  app-network:
